In [3]:
import pandas as pd
import numpy as np

In [57]:
data=pd.read_csv('data/보건복지부_공공보건 의료기관 현황_20161231.csv')
data

,연번,병원 명,설립형태,근거 법령,관계 행정기관,관계 공공단체,심평원 요양기관번호,종별구분,병상수,소재지 우편번호,주소,홈페이지,대표전화,FAX,비고
0,1,강원도 재활병원,시도립,강원도재활병원설치및운영에관한조례,강원도,해당없음,32200641,병원,165,24227,강원도 춘천시 충열로 142번길 24-16,www.grh.or.kr,033-248-7700,033-248-7723,NaN
1,2,강원도 삼척의료원,특수법인,지방의료원의 설립 및 운영에 관한 법률,보건복지부(강원도),지방의료원,32100060,종합병원,152,25920,강원도 삼척시 오십천로 418,http://ksmc.or.kr,033-572-1141,033-573-8424,NaN
2,3,강원도 영월의료원,특수법인,지방의료원의 설립 및 운영에 관한 법률,보건복지부(강원도),지방의료원,32100078,종합병원,214,26234,강원도 영월군 영월읍 중앙1로 59,http://www.youngwol.org,033-370-9117,033-370-9137,NaN
3,4,강원도 원주의료원,특수법인,지방의료원의 설립 및 운영에 관한 법률,보건복지부(강원도),지방의료원,32100086,종합병원,237,26448,강원도 원주시 서원대로 387(개운동),www.kwmc.or.kr,033-760-4500,033-761-5121,NaN
4,5,강원도 강릉의료원,특수법인,지방의료원의 설립 및 운영에 관한 법률,보건복지부(강원도),지방의료원,32100159,종합병원,137,25535,강원도 강릉시 경강로 2007(남문동 164-1),http://www.gnmc.or.kr,033-646-6910,033-610-1415,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222,216,청풍호노인사랑병원,시군구립,제천시 노인전문병원 설치및 운영에 관한 조례,충청북도,해당없음,33280576,요양병원,187,27207,충청북도 제천시 금성면 청풍호로 1147,www.cplove.co.kr,043-646-0808,043-648-5827,NaN
223,217,충주시 노인전문병원,시군구립,충주시노인전문병원설치 및 운영에관한 조례,충청북도,해당없음,33280088,요양병원,300,27442,충청북도 충주시 동량면 대전리 1686-28,www.hyolife.com,043-855-9393,043-855-8866,NaN
224,218,충청북도 충주의료원,특수법인,지방의료원의 설립 및 운영에 관한 법률,충청북도,해당없음,33100063,종합병원,292,27468,충청북도 충주시 안림로 239-50(안림동 134),www.cjmct.or.kr,043-871-0114,043-843-4231,NaN
225,219,영동군립노인전문병원,시군구립,영동군립노인전문병원설치 및 운영조례,충청북도,해당없음,33280681,요양병원,120,29131,충청북도 영동군 영동읍 대학로 290,cmisilveryd.com,043-744-9633,043-742-8275,NaN
226,220,단양군노인요양전문병원,시군구립,단양군립노인전문병원설치 및 운영조례,충청북도,해당없음,33280207,요양병원,105,27010,충청북도 단양군 단양읍 별곡6길 10,없음,043-423-8844,043-423-8874,NaN

In [58]:
addr=pd.DataFrame(data['주소'].apply(lambda v: v.split()[:2]).to_list(),
                  columns=['시도','군구'])
addr

       시도   군구
0     강원도  춘천시
1     강원도  삼척시
2     강원도  영월군
3     강원도  원주시
4     강원도  강릉시
..    ...  ...
222  충청북도  제천시
223  충청북도  충주시
224  충청북도  충주시
225  충청북도  영동군
226  충청북도  단양군

[227 rows x 2 columns]

In [59]:
addr['시도'].unique()

array(['강원도', '경기도', '경기', '경남', '창원시', '경상남도', '경상북도', '경산시', '경북',
       '인천광역시', '대구광역시', '전라남도', '대전광역시', '광주광역시', '제주특별자치도', '부산광역시',
       '전라북도', '충북', '서울특별시', '서울시', '부산특별시', '대전시', '충남', '전남', '충청남도',
       '울산광역시', '전북', '천안시', '충청북도'], dtype=object)

In [9]:
addr[addr['시도']=='창원시']

Empty DataFrame
Columns: [시도, 군구]
Index: []

In [8]:
addr.iloc[27]=['경상남도','창원시']
addr.iloc[31]=['경상남도','창원시']

In [11]:
addr[addr['시도']=='경산시']
addr.iloc[47]=['경상북도','경산시']

In [14]:
addr[addr['시도']=='천안시']
addr.iloc[209]=['충청남도','천안시']
addr.iloc[210]=['충청남도','천안시']

In [15]:
addr['시도'].unique()

array(['강원도', '경기도', '경기', '경남', '경상남도', '경상북도', '경북', '인천광역시', '대구광역시',
       '전라남도', '대전광역시', '광주광역시', '제주특별자치도', '부산광역시', '전라북도', '충북',
       '서울특별시', '서울시', '부산특별시', '대전시', '충남', '전남', '충청남도', '울산광역시', '전북',
       '충청북도'], dtype=object)

In [24]:
addr_aliases={'경기':'경기도','경남':'경상남도','경북':'경상북도',
              '충북':'충청북도','충남':'충청남도','전남':'전라남도',
              '서울시':'서울특별시','부산특별시':'부산광역시',
              '대전시':'대전광역시','강원도':'강원특별자치도',
              '전북':'전라북도'}

In [25]:
addr['시도']=addr['시도'].apply(lambda v: addr_aliases.get(v,v))
addr['시도'].unique()

array(['강원특별자치도', '경기도', '경상남도', '경상북도', '인천광역시', '대구광역시', '전라남도',
       '대전광역시', '광주광역시', '제주특별자치도', '부산광역시', '전라북도', '충청북도', '서울특별시',
       '충청남도', '울산광역시'], dtype=object)

In [26]:
addr['군구'].unique()

array(['춘천시', '삼척시', '영월군', '원주시', '강릉시', '속초시', '정선군', '수원시', '이천시',
       '안성시', '의정부시', '포천시', '파주시', '용인시', '평택시', '시흥시', '여주시', '남양주시',
       '동두천시', '안산시', '부천시', '통영시', '사천시', '창원시', '김해시', '양산시', '거창군',
       '남해군', '의령군', '포항시', '김천시', '안동시', '울진군', '경주시', '구미시', '영주시',
       '상주시', '문경시', '경산시', '의성군', '청도군', '고령군', '칠곡군', '봉화군', '울릉군',
       '부평구', '북구', '순천시', '대덕구', '태백시', '동해시', '화성시', '광산구', '남구', '중구',
       '아란13길', '서구', '전주시', '진주시', '청주시', '종로구', '성남시', '동구', '화순군',
       '강동구', '사상구', '달서구', '해운대구', '유성구', '가평군', '양주시', '고양시', '홍천군',
       '양구군', '청원군', '계룡시', '논산시', '함평군', '양평군', '수성구', '달성군', '연수구',
       '노원구', '기장군', '공주시', '강북구', '광진구', '나주시', '창녕군', '목포시', '고흥군',
       '연제구', '동매로', '서초구', '은평구', '중랑구', '강남구', '동작구', '동대문구', '양천구',
       '성동구', '송파구', '울주군', '계양구', '옹진군', '보성군', '광양시', '영광군', '무안군',
       '진도군', '강진군', '곡성군', '여수시', '신안군', '장성군', '완주군', '부안군', '정읍시',
       '남원시', '군산시', '고창군', '진안군', '제주시', '서귀포시', '천안시', '보령시', '서산시',
       '서천군', '홍성군', '제천시', '충주시', '영동군', '단양군'], dtype=object)

In [28]:
addr[addr['군구']=='아란13길']
addr.iloc[75]=['제주특별자치구','제주시']

In [30]:
addr[addr['군구']=='동매로']
addr.iloc[155]=['부산광역시','사하구']

In [31]:
addr['군구'].unique()

array(['춘천시', '삼척시', '영월군', '원주시', '강릉시', '속초시', '정선군', '수원시', '이천시',
       '안성시', '의정부시', '포천시', '파주시', '용인시', '평택시', '시흥시', '여주시', '남양주시',
       '동두천시', '안산시', '부천시', '통영시', '사천시', '창원시', '김해시', '양산시', '거창군',
       '남해군', '의령군', '포항시', '김천시', '안동시', '울진군', '경주시', '구미시', '영주시',
       '상주시', '문경시', '경산시', '의성군', '청도군', '고령군', '칠곡군', '봉화군', '울릉군',
       '부평구', '북구', '순천시', '대덕구', '태백시', '동해시', '화성시', '광산구', '남구', '중구',
       '제주시', '서구', '전주시', '진주시', '청주시', '종로구', '성남시', '동구', '화순군', '강동구',
       '사상구', '달서구', '해운대구', '유성구', '가평군', '양주시', '고양시', '홍천군', '양구군',
       '청원군', '계룡시', '논산시', '함평군', '양평군', '수성구', '달성군', '연수구', '노원구',
       '기장군', '공주시', '강북구', '광진구', '나주시', '창녕군', '목포시', '고흥군', '연제구',
       '사하구', '서초구', '은평구', '중랑구', '강남구', '동작구', '동대문구', '양천구', '성동구',
       '송파구', '울주군', '계양구', '옹진군', '보성군', '광양시', '영광군', '무안군', '진도군',
       '강진군', '곡성군', '여수시', '신안군', '장성군', '완주군', '부안군', '정읍시', '남원시',
       '군산시', '고창군', '진안군', '서귀포시', '천안시', '보령시', '서산시', '서천군', '홍성군',
       '제천시', '충주시', '영동군', '단양군'], dtype=object)

In [33]:
addr['시도군구']=addr.apply(lambda r:r['시도']+' '+r['군구'], axis=1)
addr['count']=0
addr

          시도   군구         시도군구  count
0    강원특별자치도  춘천시  강원특별자치도 춘천시      0
1    강원특별자치도  삼척시  강원특별자치도 삼척시      0
2    강원특별자치도  영월군  강원특별자치도 영월군      0
3    강원특별자치도  원주시  강원특별자치도 원주시      0
4    강원특별자치도  강릉시  강원특별자치도 강릉시      0
..       ...  ...          ...    ...
222     충청북도  제천시     충청북도 제천시      0
223     충청북도  충주시     충청북도 충주시      0
224     충청북도  충주시     충청북도 충주시      0
225     충청북도  영동군     충청북도 영동군      0
226     충청북도  단양군     충청북도 단양군      0

[227 rows x 4 columns]

In [38]:
addr_groupby=pd.DataFrame(addr.groupby(['시도','군구','시도군구'], 
                                       as_index=False).count())
addr_groupby=addr_groupby.set_index('시도군구')
addr_groupby

                  시도   군구  count
시도군구
강원특별자치도 강릉시  강원특별자치도  강릉시      4
강원특별자치도 동해시  강원특별자치도  동해시      1
강원특별자치도 삼척시  강원특별자치도  삼척시      1
강원특별자치도 속초시  강원특별자치도  속초시      1
강원특별자치도 양구군  강원특별자치도  양구군      1
...              ...  ...    ...
충청북도 영동군        충청북도  영동군      1
충청북도 제천시        충청북도  제천시      1
충청북도 청원군        충청북도  청원군      1
충청북도 청주시        충청북도  청주시      4
충청북도 충주시        충청북도  충주시      2

[141 rows x 3 columns]

In [49]:
population=pd.read_excel('data/행정구역_시군구_별__성별_인구수_20230907141126.xlsx')
population

          시도       군구      총인구수     남자인구수     여자인구수
0         전국       전국  51377213  25596921  25780292
1      서울특별시       소계   9409466   4554020   4855446
2      서울특별시   　　　종로구    140032     67682     72350
3      서울특별시    　　　중구    121482     58840     62642
4      서울특별시   　　　용산구    216547    103993    112554
..       ...      ...       ...       ...       ...
288     경상남도   　　　거창군     60184     29607     30577
289     경상남도   　　　합천군     41531     20239     21292
290  제주특별자치도       소계    676489    338622    337867
291  제주특별자치도   　　　제주시    492379    245974    246405
292  제주특별자치도  　　　서귀포시    184110     92648     91462

[293 rows x 5 columns]

In [50]:
population['시도'].unique()

array(['전국', '서울특별시', '부산광역시', '대구광역시', '인천광역시', '대전광역시', '울산광역시',
       '세종특별자치시', '경기도', '강원특별자치도', '충청북도', '충청남도', '전라북도', '전라남도',
       '경상북도', '경상남도', '제주특별자치도'], dtype=object)

In [51]:
population['군구']=population['군구'].apply(lambda v:v.strip())
population['군구'].unique()

array(['전국', '소계', '종로구', '중구', '용산구', '성동구', '광진구', '동대문구', '중랑구', '성북구',
       '강북구', '도봉구', '노원구', '은평구', '서대문구', '마포구', '양천구', '강서구', '구로구',
       '금천구', '영등포구', '동작구', '관악구', '서초구', '강남구', '송파구', '강동구', '서구',
       '동구', '영도구', '부산진구', '동래구', '남구', '북구', '해운대구', '사하구', '금정구',
       '연제구', '수영구', '사상구', '기장군', '수성구', '달서구', '달성군', '군위군', '중구영종출장소',
       '중구용유출장소', '미추홀구', '연수구', '남동구', '부평구', '계양구', '서구검단출장소', '강화군',
       '옹진군', '광산구', '유성구', '대덕구', '울주군', '세종시', '수원시', '장안구', '권선구',
       '팔달구', '영통구', '성남시', '수정구', '중원구', '분당구', '의정부시', '안양시', '만안구',
       '동안구', '부천시', '광명시', '평택시', '송탄출장소', '안중출장소', '동두천시', '안산시', '상록구',
       '단원구', '고양시', '덕양구', '일산동구', '일산서구', '과천시', '구리시', '남양주시', '풍양출장소',
       '오산시', '시흥시', '군포시', '의왕시', '하남시', '용인시', '처인구', '기흥구', '수지구',
       '파주시', '이천시', '안성시', '김포시', '화성시', '화성시동부출장소', '화성시동탄출장소', '광주시',
       '양주시', '포천시', '여주시', '연천군', '가평군', '양평군', '춘천시', '원주시', '강릉시',
       '동해시', '태백시', '속초시', '삼척시', '홍천군', '횡성군', '영월군', '평창군', '정선군',
       '철원군', '화천군', '양구군', '인제군', '고성군', '양양군', '청주시', '서원구', '청원구',
       '상당구', '흥덕구', '충주시', '제천시', '보은군', '옥천군', '영동군', '증평군', '진천군',
       '괴산군', '음성군', '단양군', '당진시', '천안시', '동남구', '서북구', '공주시', '보령시',
       '아산시', '서산시', '논산시', '계룡시', '금산군', '부여군', '서천군', '청양군', '홍성군',
       '예산군', '태안군', '전주시', '완산구', '덕진구', '전주시효자출장소', '군산시', '익산시',
       '익산시함열출장소', '정읍시', '남원시', '김제시', '완주군', '진안군', '무주군', '장수군', '임실군',
       '순창군', '고창군', '부안군', '목포시', '여수시', '순천시', '나주시', '광양시', '담양군',
       '곡성군', '구례군', '고흥군', '보성군', '화순군', '장흥군', '강진군', '해남군', '영암군',
       '무안군', '함평군', '영광군', '장성군', '완도군', '진도군', '신안군', '포항시', '경주시',
       '김천시', '안동시', '구미시', '영주시', '영천시', '상주시', '문경시', '경산시', '의성군',
       '청송군', '영양군', '영덕군', '청도군', '고령군', '성주군', '칠곡군', '예천군', '봉화군',
       '울진군', '울릉군', '창원시', '의창구', '성산구', '마산합포구', '마산회원구', '진해구', '진주시',
       '통영시', '사천시', '사천남양출장소', '김해시', '장유출장소', '밀양시', '거제시', '양산시',
       '양산시웅상출장소', '의령군', '함안군', '창녕군', '남해군', '하동군', '산청군', '함양군', '거창군',
       '합천군', '제주시', '서귀포시'], dtype=object)

In [55]:
population['시도군구']=population.apply(lambda r:r['시도']+' '+r['군구'], axis=1)
population=population[population['군구']!='전국']
population=population[population['군구']!='소계']
population=population.set_index('시도군구')
population

                   시도    군구    총인구수   남자인구수   여자인구수
시도군구
서울특별시 종로구       서울특별시   종로구  140032   67682   72350
서울특별시 중구        서울특별시    중구  121482   58840   62642
서울특별시 용산구       서울특별시   용산구  216547  103993  112554
서울특별시 성동구       서울특별시   성동구  278750  135346  143404
서울특별시 광진구       서울특별시   광진구  336446  161828  174618
...               ...   ...     ...     ...     ...
경상남도 함양군         경상남도   함양군   37117   18013   19104
경상남도 거창군         경상남도   거창군   60184   29607   30577
경상남도 합천군         경상남도   합천군   41531   20239   21292
제주특별자치도 제주시   제주특별자치도   제주시  492379  245974  246405
제주특별자치도 서귀포시  제주특별자치도  서귀포시  184110   92648   91462

[275 rows x 5 columns]

In [56]:
addr_polulation=pd.merge(addr_groupby,population, how='inner')
addr_polulation

          시도   군구  count    총인구수   남자인구수   여자인구수
0    강원특별자치도  강릉시      4  210122  104154  105968
1    강원특별자치도  동해시      1   88951   45203   43748
2    강원특별자치도  삼척시      1   63086   32028   31058
3    강원특별자치도  속초시      1   82326   40773   41553
4    강원특별자치도  양구군      1   21255   11149   10106
..       ...  ...    ...     ...     ...     ...
132     충청북도  단양군      1   27728   14119   13609
133     충청북도  영동군      1   44436   22252   22184
134     충청북도  제천시      1  130858   65791   65067
135     충청북도  청주시      4  851653  430330  421323
136     충청북도  충주시      2  207998  105473  102525

[137 rows x 6 columns]